version: '3.1'
services:
    frontend:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes:
        - /app/node_modules
        - .:/app
      environment:
        CHOKIDAR_USEPOLLING: "true"
